/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.tutorial;

public class App {
    public String getGreeting() {
        return "Hello World! John Said.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Hello John!");
        
    }
}
