package com.huaxia.test;

public class Computer {
	String screensize;
	String brand;
	float batteryLevel;

	// this is constructor generated by eclipse
	public Computer(String screensize, String brand, float batteryLevel) {
		this.screensize = screensize;
		this.brand = brand;
		this.batteryLevel = batteryLevel;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Computer [screensize=" + screensize + ", brand=" + brand + "]";
	}

	public static void main(String[] args) {
		Computer newComputer = new Computer("17\"","Dell",  80);		
//		String brand = "dell";
//		float battery = 80;
//		newComputer.batteryLevelBrand(brand, battery);
//		System.out.println("The battery of this " + newComputer.brand + " computer has " + newComputer.batteryLevel + "%.");
		System.out.println(newComputer);
		newComputer.setBatteryLevel(60);
		System.out.println(newComputer);
	}

	public String getScreensize() {
		return screensize;
	}

	public void setScreensize(String screensize) {
		this.screensize = screensize;
	}

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public float getBatteryLevel() {
		return batteryLevel;
	}

	public void setBatteryLevel(float batteryLevel) {
		this.batteryLevel = batteryLevel;
	}
}

